language: node_js
node_js:
  - "8"
sudo: enabled
before_install:
- command -v nvm
install:
- sudo apt-get install libtool
- sudo apt-get install automake
- sudo apt-get install autoconf
- npm install -g codecov
- npm install
- cd /home/travis/build/KnoxDevTeam/Lavender
script:
- npm test
- codecov
    
  
after_success:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
