lnaguage: node_js
script: 
node_js:
  - node
cache:
  directories:
    - node_modules
notifications:
  email:
    on_success: always
    on_failure: always
before_install:
  - 'sudo apt-get update'
  - 'sudo apt-get upgrade'
  - 'npm update'
  - 'npm i -g npm && npm i --save'
install:
  - 'sudo npm install'
  - 'npm install -g codecov'
script: 
  - 'npm test'
  - 'codecov'
dist: trusty
sudo: required
