version: 2
jobs:
  build:
    docker:
      - image: node:7.4.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm i -g eslint && npm i --save
      - run:
          name: ESLint Check
          command: npm run lint
